# Generated by Django 4.0.4 on 2022-12-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTaller', models.IntegerField()),
                ('nombreTaller', models.CharField(max_length=40)),
                ('descripcionTaller', models.CharField(max_length=300)),
                ('imagen', models.ImageField(null=True, upload_to='items_taller')),
            ],
            options={
                'db_table': 'db_items_taller',
            },
        ),
        migrations.CreateModel(
            name='TipoTaller',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_tipo_taller',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='usuariosadulmayor')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuarioadmin',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='usuariosadmin')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_usuario_administrador',
            },
        ),
        migrations.CreateModel(
            name='Usuariofuncionario',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='usuariosfuncionario')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_usuario_funcionario',
            },
        ),
        migrations.CreateModel(
            name='Usuarioinstructor',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='usuariosinstructor')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_usuario_instructor',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(null=True, upload_to='talleres')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipotaller')),
            ],
            options={
                'db_table': 'db_taller',
            },
        ),
        migrations.CreateModel(
            name='CarroTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taller')),
            ],
            options={
                'db_table': 'db_carrotaller',
            },
        ),
    ]
