# Generated by Django 4.0.4 on 2022-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_materiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='imagen',
            field=models.ImageField(null=True, upload_to='materiales'),
        ),
    ]
